// <auto-generated />
using System;
using FurnitureApi.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FurnitureApi.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231112180229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FurnitureApi.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1000,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(4480),
                            IsDeleted = false,
                            Name = "Sofa"
                        },
                        new
                        {
                            Id = 1002,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(4510),
                            IsDeleted = false,
                            Name = "Chair"
                        },
                        new
                        {
                            Id = 1003,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(4510),
                            IsDeleted = false,
                            Name = "Table"
                        },
                        new
                        {
                            Id = 1004,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(4510),
                            IsDeleted = false,
                            Name = "Bed"
                        });
                });

            modelBuilder.Entity("FurnitureApi.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1000,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(4990),
                            Description = "Lorem ipsum Dolor sit amet",
                            IsDeleted = false,
                            Price = 19.399999999999999,
                            Rating = 4.5,
                            Title = "Comfortable Sofa"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1002,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(5000),
                            Description = "Lorem ipsum Dolor sit amet",
                            IsDeleted = false,
                            Price = 29.989999999999998,
                            Rating = 4.0,
                            Title = "Leather Chair"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1003,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(5000),
                            Description = "Lorem ipsum Dolor sit amet",
                            IsDeleted = false,
                            Price = 39.990000000000002,
                            Rating = 4.2000000000000002,
                            Title = "Modern Table"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1004,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(5000),
                            Description = "Lorem ipsum Dolor sit amet",
                            IsDeleted = false,
                            Price = 99.989999999999995,
                            Rating = 4.7999999999999998,
                            Title = "King-sized Bed"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1000,
                            CreatedDate = new DateTime(2023, 11, 12, 21, 2, 29, 419, DateTimeKind.Local).AddTicks(5000),
                            Description = "Lorem ipsum Dolor sit amet",
                            IsDeleted = false,
                            Price = 59.399999999999999,
                            Rating = 3.5,
                            Title = "Sofa Later"
                        });
                });

            modelBuilder.Entity("FurnitureApi.Domain.Entities.Product", b =>
                {
                    b.HasOne("FurnitureApi.Domain.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FurnitureApi.Domain.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
